### ISSUE TITLE
can't install the docker version

### ISSUE THREAD

**Issue by JosePortoMonokera** [gorules/zen#263]
I can't install the Docker Compose version. Under the log of gorules-admin-1 container I have the following message: 

2024-10-21 10:53:25 {"level":50,"time":1729518805364,"pid":1,"hostname":"7864bbf30c4b","name":"system","err":{"message":"self-signed certificate in certificate chain: self-signed certificate in certificate chain","name":"Error","stack":"Error: self-signed certificate in certificate chain\n    at AxiosError.from (/app/main.js:100:59425)\n    at RedirectableRequest.handleRequestError (/app/main.js:102:8966)\n    at RedirectableRequest.emit (node:events:518:28)\n    at ei.<computed> (/app/main.js:398:149870)\n    at ClientRequest.emit (node:events:518:28)\n    at emitErrorEvent (node:_http_client:103:11)\n    at TLSSocket.socketErrorListener (node:_http_client:506:5)\n    at TLSSocket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at CE.request (/app/main.js:102:22804)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\ncaused by: Error: self-signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)\n    at TLSSocket.emit (node:events:518:28)\n    at TLSSocket._finishInit (node:_tls_wrap:1078:8)\n    at ssl.onhandshakedone (node:_tls_wrap:864:12)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http","fetch"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.7.2","Content-Length":"156","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://portal.gorules.io/api","method":"post","url":"/environments/validate","data":"{\"licenseKey\":\"4195307a-3877-4762-8f15-XXXXXXXXXX\",\"clientDatabaseId\":\"742822669023XXXXXXXX\",\"clientOrganisationId\":\"f40630b6-38bb-4ae5-9f19-32eXXXXXXXXXX\"}","axios-retry":{"retryCount":0,"lastRequestTime":1729518805207}},"code":"SELF_SIGNED_CERT_IN_CHAIN","status":null},"msg":"failed to fetch license"}
2024-10-21 10:53:25 {"level":50,"time":1729518805367,"pid":1,"hostname":"7864bbf30c4b","name":"system","err":{"type":"Error","message":"incorrect license, failed to start the service","stack":"Error: incorrect license, failed to start the service\n    at /app/main.js:110:22721\n    at step (/app/main.js:110:21088)\n    at Object.next (/app/main.js:110:20390)\n    at database_asyncGeneratorStep (/app/main.js:110:19480)\n    at _next (/app/main.js:110:19707)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"},"msg":"application startup error"}
2024-10-21 10:53:24 (node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2024-10-21 10:53:24 (Use `node --trace-deprecation ...` to show where the warning was created)

The license is new and is the sole change on the compose script on documentation. even DB's user and password were the same.

Any idea of what may be happening? 

PS:// licenseKey, clientDatabaseID and clientOrganisationId have being tampered on purpose here for obvious reasons.

**Comment by stefan-gorules** [comment]
Hi @JosePortoMonokera, this looks like an issue with the SSL Certificate while the request is being made. For some reason Docker runner is unable to communicate with https://portal.gorules.io. Are you able to do do:

```bash
curl -v https://portal.gorules.io/api/health
```

And post the results? Happy to take a look at this privately as it's not connected to the open source.
