### ISSUE TITLE
Number conversion panicked

### ISSUE THREAD

**Issue by slice-Adityaraj** [gorules/zen#291]
https://github.com/gorules/zen/blob/b2b22a74b2d0711e3f82f66f51d80a3a954ea0e3/core/expression/src/variable/conv.rs#L16C17-L16C95

Go application panics suddenly with the log below.
```
thread '<unnamed>' panicked at core/expression/src/variable/conv.rs:16:70:
Allowed number: ErrorString("Invalid decimal: unknown character")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
```

This error handling needs to be added in the line above.

**Comment by stefan-gorules** [comment]
Hi, would you be able to provide a reproduction and post the issue on https://github.com/gorules/zen-go/ instead. Thank you!
